title: Call for Submissions
description: The Electronic Literature Organization (ELO) seeks submissions for Volume 5 of the Electronic Literature Collection.
url: https://eliterature.github.io/elc5-info
baseurl: /elc5-info
# Using default Jekyll theme with custom CSS
plugins:
  - jekyll-feed